---
# {{ ansible_managed }}

filebeat.inputs:

{% for fb in filebeat %}
- type: log
  enabled: true
  paths:
{% for file in fb.files %}
    - {{ file }}
{% endfor %}
  fields:
    type: {{ fb.name }}
  fields_under_root: true
  scan_frequency: 5s

{% endfor %}

output.logstash:
  hosts: ["{{ elk_elastic_address }}"]

xpack:
  enabled: false

name: {{ inventory_hostname }}
logging.level: error
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat.log
  rotateeverybytes: 10485760 # = 10MB
  keepfiles: 7
  rotateonstartup: true
