---

all:
  hosts:
    vpn.les.pne.io:
      ansible_user: root
      ansible_host: 0.0.0.0
      ansible_port: 22022

# add root ssh key
      users:
        - name: root
          authorized:
            - id_rsa/amelnikov.pub
            - id_rsa/es.pub
            - id_rsa/vlad.pub

# enable ip forward
      ip_forward: true

# configure openvpn server
      openvpn_gen_key: true
      openvpn_gen_client_key: true
      openvpn_port: 8443
      openvpn_proto: tcp
      openvpn_ipv4_forward: true
      openvpn_ip_network: 192.168.123
      openvpn_server_address: 0.0.0.0
# create vpn clients configs
# create ccd files. ip push 11-12,13-14,15-16....
      openvpn_client:
        - "les001"
        - "les002"
        - "les003"
        - "les004"
        - "les005"

# configure LetsEncrypt
      le_mail: my_mail
      le_fqdn: fqdn_name_server

# enable expose ports for docker. default false.
# 9115 blackbox-exporter
# 9100 node-exporter
# 9090 prometheus
# 3000 grafana
# 9093 alertmanager
# 8080 alertmanager-bot
#      monitoring_expose_port: true

# configure grafana 
      grafana_url: "https://fqdn_name_server"
      grafana_password: "xxxxxxxxxxxxxx"

# configure prometheus 
# expoeters
      prometheus_node_exporters:
        - pi:        # name 
          labels:                 # labels
            - state: prod
            - team: sysops
          targets:
            - 192.168.123.11:9100
            - 192.168.123.13:9100
#            - 192.168.123.15:9100
#            - 192.168.123.17:9100
#            - 192.168.123.19:9100

# web test status 200
      prometheus_blackbox_web:
        - grafana:
          labels:
            - state: prod
            - team: sysops
          targets:
            - "{{ grafana_url }}"
#        - pi:
#          labels:
#            - state: prod
#            - team: sysops
#          targets:
#            - http://192.168.123.11
#            - http://192.168.123.13
#            - http://192.168.123.15
#            - http://192.168.123.17
#            - http://192.168.123.19

# tcp potr listing
      prometheus_blakbox_tcp:
        - ssh:
          labels:
            - state: prod
            - team: sysops
          targets:
            - 192.168.123.11:22
            - 192.168.123.13:22
#            - 192.168.123.15:80
#            - 192.168.123.17:80
#            - 192.168.123.19:80

# configure telegram bot 
      telegram_bot_token: "xxxxx:yyyyyyyy" # 
      telegram_admin_id: 
        - 151311955 # amelnikov

hard_lite:
  hosts:
    vpn.les.pne.io:

docker_ce:
  hosts:
    vpn.les.pne.io:

docker_compose_ce:
  hosts:
    vpn.les.pne.io:

daemontools:
  hosts:
    vpn.les.pne.io:

users:
  hosts:
    vpn.les.pne.io:

openvpn:
  hosts:
    vpn.les.pne.io:

monitoring:
  hosts:
    vpn.les.pne.io:
